### ISSUE TITLE
The of installation scLearn failed 

### ISSUE THREAD

**Issue by HuaZou** [bm2-lab/scLearn#1]
Hi, When I used the command **devtools::install_github("bm2-lab/scLearn")**, I got the bug information:  

```bash
Installing package into ‘C:/Software/R/Rlibrary’
(as ‘lib’ is unspecified)
* installing *source* package 'scLearn' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dml' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'scLearn'
* removing 'C:/Software/R/Rlibrary/scLearn'
```

I have checked my R version which was version 4.0.2 and the R version for package more than 3.6.1. By the way I also reinstalled the *dml* package, but it came to failed again. Have you ever met this bug or how could I fix it? THX

**Comment by lxhuang7** [comment]
Not from the dev team, but I was able to install the package using the command below,
BiocManager::install('bm2-lab/scLearn')

**Comment by HuaZou** [comment]
> Not from the dev team, but I was able to install the package using the command below,
> BiocManager::install('bm2-lab/scLearn')

THX, but unfortunately the bug appeared. I have no idea to deal with it.  The details of this bug were in Screenshot, I wish it will be help for others to figure this bug out. Anyway, thanks for your reply. 
![1604568217](https://user-images.githubusercontent.com/37990676/98222354-ae4b0780-1f8b-11eb-8870-34ffa2d55b6c.jpg)

**Comment by BinDuan** [comment]
Sorry for this. To make sure it works, I suggest you use R version 3.6.1.

**Comment by CJ-Liu** [comment]
I have tried the installation under R 3.6.3, and encountered the same error.
Try：Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
and  run：devtools::install_github("bm2-lab/scLearn")
it worked well.

**Comment by HuaZou** [comment]
> I have tried the installation under R 3.6.3, and encountered the same error.
> Try：Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
> and run：devtools::install_github("bm2-lab/scLearn")
> it worked well.

@CJ-Liu  What an Unbelieveable solution  it is !!!  Thanks for your helpful code. It worked.

**Comment by ElyasMo** [comment]
> I have tried the installation under R 3.6.3, and encountered the same error.
> Try：Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
> and run：devtools::install_github("bm2-lab/scLearn")
> it worked well.

Thanks, you've rescued me.
