### ISSUE TITLE
Downloading the pre-trained models not possible

### ISSUE THREAD

**Issue by jakalssj3** [bm2-lab/scLearn#2]
It is not possible to download the pre-trained models! It requires to create an account, verify it by the passcode sent by SMS, but each time the process fails with no explanation whatsoever.

**Comment by BinDuan** [comment]
Sorry for this. To download the pre-trained models, you need have an account for jianguoyun. If you can not sign in jianguoyun, you can contact their costomer server. For convenience, here is a jianguoyun account you can use for free. Accout: bioinfo_db@tongji.edu.cn    Password: db123456

**Comment by jakalssj3** [comment]
Great, thank you for sharing the account details!
