### ISSUE TITLE
How to distinguish similar cell types?

### ISSUE THREAD

**Issue by sajuukLyu** [bm2-lab/scLearn#3]
Dear authors,
  I find it is hard to distinguish some cell types if they are similar in the reference dataset using default parameters. There are too many 'unassigned' in the output. I wonder how to adjust the parameters in scLearn_model_learning() to get a less strict model? Thanks.

**Comment by BinDuan** [comment]
Yes, it is hard to distinguish similar cell type for single cell assignment. You can adjust three parameters to get a less strict model and assignment results: (1). parameter "cutoff" in function "scLearn_model_learning". The default is cutoff=0.01 and you can set the smaller value, such as 0.001. (2). parameters "vote_rate" and "diff" in  function "scLearn_cell _assignment". The default is vote_rate=0.6 and diff=0.05. You can set vote_rate=0.5 and diff=0.01. Hope it helps!
