### ISSUE TITLE
Error when run the example data

### ISSUE THREAD

**Issue by chenatf** [bm2-lab/scLearn#4]
Hello, I encounter a error when run the: 
scLearn_predict_result<-scLearn_cell_assignment(scLearn_model_learning_result,data_qc_query$expression_profile). 
The message is:
[1] "The number of missing features in the query data is  0 "
[1] "The rate of missing features in the query data is  0 "
Error in scLearn_model_learning_result$trans_matrix_learned[[r]] %*% expression_profile_query_hvg : 
  non-conformable arguments

could you give me some advice for this error? The R version is 4.0.2.

**Comment by BinDuan** [comment]
> Hello, I encounter a error when run the:
> scLearn_predict_result<-scLearn_cell_assignment(scLearn_model_learning_result,data_qc_query$expression_profile).
> The message is:
> [1] "The number of missing features in the query data is 0 "
> [1] "The rate of missing features in the query data is 0 "
> Error in scLearn_model_learning_result$trans_matrix_learned[[r]] %*% expression_profile_query_hvg :
> non-conformable arguments
> 
> could you give me some advice for this error? The R version is 4.0.2.

Sorry for this bug. Now I have revised function "scLearn_cell_assignment". Now it works fine. Please reinstall scLearn and try it again. Thank you for your attention!

**Comment by chenatf** [comment]
Thanks for your reply. The problem has beend solved.
