### ISSUE TITLE
run into error when performing cell assignment codes

### ISSUE THREAD

**Issue by whateverxzy** [bm2-lab/scLearn#7]
Dear authors,
     When I ran this code"scLearn_predict_result<-scLearn_cell_assignment(scLearn_model_learning_result,data_qc_query$expression_profile,diff=0.05,threshold_use=TRUE,vote_rate=0.6)", there was a error:
Error in scLearn_cell_assignment(scLearn_model_learning_result, data_qc_query$expression_profile,  : 
  参数没有用(threshold_use = TRUE).
Even if I changed the value of threshold_use to FALSE, it still has problem.
Can you explain to me that why this happenen? Thank you for your time.

**Comment by BinDuan** [comment]
> Dear authors,
> When I ran this code"scLearn_predict_result<-scLearn_cell_assignment(scLearn_model_learning_result,data_qc_query$expression_profile,diff=0.05,threshold_use=TRUE,vote_rate=0.6)", there was a error:
> Error in scLearn_cell_assignment(scLearn_model_learning_result, data_qc_query$expression_profile, :
> 参数没有用(threshold_use = TRUE).
> Even if I changed the value of threshold_use to FALSE, it still has problem.
> Can you explain to me that why this happenen? Thank you for your time.

I guess you installed scLearn a few weeks before. We made some updates before, including add some parameters, so please reinstall scLearn, then this error won't happen. Sorry for the inconvenience.
