### ISSUE TITLE
how to get the accuracy that you provided in the paper

### ISSUE THREAD

**Issue by whateverxzy** [bm2-lab/scLearn#9]
Dear authors,
When I ran the codes that you shared in the github, what I got are as follows:
"[1] "The number of missing features in the query data is  79 "
[1] "The rate of missing features in the query data is  0.0671768707482993 "'
and the reference dataset is deng-reads.rds, the query dataset is zeisel.rds.
But I can't get the accuracy that you provided in the papers.
 Like this "deng_zeisel   scLearn 0.996"
Is something missing when I ran the codes.
I will appreciate it  if you can helo me out of this. Thank you for your time.

**Comment by BinDuan** [comment]
We didn't offer the code to calculate accuracy, because it wasn't our purpose. Besides, it is easy to calculate accuracy, because it is a common used metric. You can write the code to calculate "accuracy" by yourself or load other R package to calculate it.

**Comment by BinDuan** [comment]
> Dear authors,
> When I ran the codes that you shared in the github, what I got are as follows:
> "[1] "The number of missing features in the query data is 79 "
> [1] "The rate of missing features in the query data is 0.0671768707482993 "'
> and the reference dataset is deng-reads.rds, the query dataset is zeisel.rds.
> But I can't get the accuracy that you provided in the papers.
> Like this "deng_zeisel scLearn 0.996"
> Is something missing when I ran the codes.
> I will appreciate it if you can helo me out of this. Thank you for your time.

We didn't offer the code to calculate accuracy, because it wasn't our purpose. Besides, it is easy to calculate accuracy, because it is a common used metric. You can write the code to calculate "accuracy" by yourself or load other R package to calculate it
